    float sum = 0.0;
    float frequency = pow(2, firstOctave);
	const float persistence = 0.6;
    float amplitude = pow(persistence, firstOctave);
    for(int i=firstOctave; i < firstOctave + accumOctaves;i++)
    {
		uvw -= iTime * TimeScale;
        sum += perlin(uvw, frequency, SliceNum, Coverage) * amplitude;
        frequency *= 2.0;
        amplitude *= persistence;
    }
	return sum;
    